ideas/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # RESTful routes
  get('/', {to: 'ideas#index', as: 'root'})
  # get('/ideas/new',{to: 'ideas#new'})
  # get('/ideas/:id',{to: 'ideas#show', as: :idea })
  # delete('/ideas/:id',{to: 'ideas#destroy'})
  # idea('/ideas/',{to: 'ideas#create'})
  # get('/ideas/:id/edit',{to: 'ideas#edit', as: :edit_idea})
  # patch('/ideas/:id', {to: 'ideas#update'})

  resources :ideas do
    resources :reviews, only:[:create, :destroy]
    
    resources :likes, shallow: true, only:[:create, :destroy]
    get :liked, on: :collection
  end

  resources :users, only:[:new, :create]
  resource :session, only:[:new, :create, :destroy]

end

ideas/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    
    if user.is_admin?
      can :manage, :all  
    end
    
    
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    alias_action(:create, :read, :update, :destroy, to: :crud)

    can(:crud, Idea) do |idea|
      user == idea.user
    end

    can(:crud, Review) do |review|
      user == review.user
    end

    can(:like, Idea) do|idea|
      user.persisted?
    
    end

    can(:destroy, Like) do |like|
      like.user == user
    end
    
  end
end

ideas/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ideas/app/models/idea.rb
class Idea < ApplicationRecord

    #ASSOCIATIONS
    has_many :reviews, dependent: :destroy
    belongs_to :user
    
    has_many :likes, dependent: :destroy
    has_many :likers, through: :likes, source: :user
    
    #VALIDATIONS
    validates :title, presence: {message: "must be provided"}, uniqueness: true
    validates :description, presence: true, length: { minimum: 2, maximum: 200 }

end

ideas/app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :idea

  validates(
    :idea_id,
    uniqueness: {
      scope: :user_id
    }
  )
end

ideas/app/models/review.rb
class Review < ApplicationRecord
  #ASSOCIATIONS
  belongs_to :idea
  belongs_to :user

  #VALIDATIONS
  validates :body, length: { minimum: 2, maximum: 200 }
end

ideas/app/models/user.rb
class User < ApplicationRecord
    
    #ASSOCIATIONS
    has_secure_password
    has_many :ideas, dependent: :destroy
    has_many :reviews, dependent: :destroy
    
    has_many :likes, dependent: :destroy
    has_many :liked_ideas, through: :likes, source: :idea
    
    #VALIDATIONS
    validates :first_name, :last_name, :email, :password, presence:true

    def full_name
        "#{first_name} #{last_name}"
    end
end

ideas/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def current_user
        @current_user ||= User.find_by_id session[:user_id]
    end
    helper_method :current_user

    def user_signed_in?
        current_user.present?
    end
    helper_method :user_signed_in?

    def authenticate_user!
        redirect_to new_session_path, alert: "Please sign in" unless user_signed_in?
    end
    
end

ideas/app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

    before_action :find_idea, only: [:edit, :update, :show, :destroy]
    before_action :authenticate_user!, except: [:index, :show]
    before_action :authorize_user!, only: [:update, :destroy]

    def index
        @ideas = Idea.all.order(created_at: :desc)
        
    end
        

    def show
          @reviews = @idea.reviews.order(created_at: :desc)
          @review = Review.new
    end   

    def destroy
        @idea.destroy
        redirect_to ideas_path, alert: 'Idea Deleted' 
    end

    def new
        @idea = Idea.new
    end

    def create
       
        @idea = Idea.new(idea_params)
        @idea.user = current_user
        
        if @idea.save
            redirect_to idea_path(@idea.id), notice: 'Idea Created Successfully!' 
        else
            render :new
        end

    end

    def edit
        
    end

    def update
        if @idea.update(idea_params)
            redirect_to idea_path(@idea.id)
        else
            render :edit
        end 
    end

    def liked
        @idea = current_user.liked_ideas
    end

    private 

    def find_idea
        @idea = Idea.find params[:id]
    end

    def idea_params
        params.require(:idea).permit(:title,:description)
    end

    def authorize_user!
        redirect_to root_path, alert: "Not Authorized!" unless can?(:crud, @idea)
    end

end

ideas/app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
        idea = Idea.find params[:idea_id]
        like = Like.new(idea: idea, user: current_user)
         if can?(:like, idea)
            if like.save
                flash[:notice] = "Idea Liked"
            else
                flash[:alert] = like.errors.full_messages.join(', ')
            end
        
         end

        redirect_to root_path(idea)
    end
    
    def destroy
        like = Like.find params[:id]
         if can?(:destroy, like)
            if like.destroy
                # flash[:alert] = "Idea Unliked"
            else
                flash[:alert] = like.errors.full_messages.join(', ')
            end
        
         end
        redirect_to root_path(like.idea)
    end
    
end

ideas/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    
    before_action :find_idea 
    before_action :authenticate_user!

    def create
        @review  = Review.new(review_params)
        @review.idea = @idea
        @review.user = current_user

        if @review.save
            redirect_to idea_path(@idea.id), notice: 'Review created!'
        else
            @reviews = @idea.reviews.order(created_at: :desc)
            render 'ideas/show'
        end

    end
    
    def destroy
        @review = Review.find params[:id]

        if can?(:crud, @review)
            @review.destroy
            redirect_to idea_path(@idea), alert: 'Review Deleted'
        else
            redirect_to root_path, alert: 'Not Authorized'
        end
    end
    
    private

    def find_idea
        @idea = Idea.find params[:idea_id]
    end

    def review_params
        params.require(:review).permit(:body)
    end
    
end

ideas/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new

    end

    def create
        @user = User.find_by_email params[:email]
        if @user && @user.authenticate(params[:password])
            session[:user_id] = @user.id  
            redirect_to root_path, notice: "logged in"
        else
            flash.now[:alert] = "wrong email or password"
            render :new
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path, alert: "logged out"
    end

end

ideas/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create 
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path, notice: 'Logged in'
        else
            render :new
        end
    end

    private

    def user_params
        params.require(:user).permit(
            :first_name,
            :last_name,
            :email,
            :password,
            :password_confirmation
        )
    end

end

ideas/app/helpers/application_helper.rb
module ApplicationHelper
end

ideas/app/views/ideas/edit.html.erb
<div class="container-fluid">

    <% if @idea.errors.any? %>
            <% @idea.errors.full_messages.each do |msg|%>
                <div class="alert alert-warning font-s" role="alert"> 
                    <%= msg %>
                </div>
            <% end%>
    <% end%>

    <%= form_with(model: @idea) do |form|%>

    <div>
        <%= form.label :title, class:"font"%>
        <br>
        <%= form.text_field :title, class:"form-control font-s" %>
    </div>
   <br>
    <div>
        <%= form.label :description, class:"font"%>
        <br>
        <%=  form.text_area :description, class:"form-control example font-s"%>
    </div>
    <br>
    <%= form.submit :'Update Idea', class: 'btn btn-outline-info font-s' %>
    <% end%>
</div>

ideas/app/views/ideas/index.html.erb
<div class="container-fluid">
    <ul class="list-group list-group-flush">
    <br>
        <% @ideas.each do |idea|%>
            
            <li class="list-group-item"
              
                <h3 class=" heading" >
                    <%= link_to idea.title, idea_path(idea.id), :class => " card-title font-family font-weight-bold text-info" %>
                </h3>
                <div class=" body font text-dark">
                    <%= idea.description%>
                </div>
                <br>
                
                    <div class = "row ">
                     
                    <% if can?(:like, idea)%>

                        <% like = idea.likes.find_by(user: current_user) %>
                        <% if like.present? %>
                             
                            <div class = "col ">
                                <%= link_to "Liked", like_path(like),method: :delete,:class => "btn btn-outline-info font-s"  %>
                               
                            </div>
                            <p  class="col font-s text-secondary">
                                    liked by: <%= like.user.full_name %>
                            </p>
                        
                        <% else %>
                            <div class = "col ">
                                <%= link_to "Like", idea_likes_path(idea),method: :post,:class => " btn btn-outline-info font-s"  %>
                            </div>
                        <% end %>
                        
                        <div class = "col-auto text-dark font-s">
                            <div>Likes: <%= idea.likes.count %></div>
                        </div>
                        
                    <% end %>
                    </div>

            </li>
            <br>
        <% end %>
    </ul>
</div>










  

ideas/app/views/ideas/new.html.erb
<div class="container-fluid">

    <% if @idea.errors.any? %>
            <% @idea.errors.full_messages.each do |msg|%>
                <div class="alert alert-warning font-s" role="alert"> 
                    <%= msg %>
                </div>
            <% end%>
    <% end%>

    <%= form_with(model: @idea) do |form|%>

    <div>
        <%= form.label :title, class:"font"%>
        <br>
        <%= form.text_field :title, class:"form-control font-s"%>
    </div>
    <br>
    <div>
        <%= form.label :description, class:"font"%>
        <br>
        <%= form.text_area :description, class:"form-control font-s" %>
    </div>
    <br>
    <%= form.submit :'Create Idea', class: 'btn btn-outline-info font-s' %>  
<% end%>
</div>

ideas/app/views/ideas/show.html.erb
<div class="container-fluid">
    <br>
    <h4 class= "example font-family text-dark">
        <%= @idea.title%>
   </h4>
    
    <p class= "example font text-dark"> 
        <%= @idea.description%>
    </p>

    <p  class="font-s text-secondary">
    Posted <%= time_ago_in_words(@idea.created_at) %> ago
    </p>

     <p  class="font-s text-secondary">
    Created by: <%= @idea.user.full_name %>
    </p>

    <% if can?(:crud, @idea)%>
        <%= link_to "Edit", edit_idea_path(@idea.id) ,:class => 'btn btn-outline-info font-s' %>
        <%= link_to "Delete", idea_path(@idea.id), :class => 'btn btn-outline-info font-s', method: :delete, data:{confirm:"Are you sure?"} %>
    <% end %>

<%= form_with(model:[@idea, @review]) do |f|%>
        <div>
        <br>
            <h5 class="font"><%= f.label :Review %></h5>
            <%= f.text_area :body, class:"form-control font-s", :placeholder => "what's on your mind?" %>
        </div>
        <br>
        <%= f.submit :Submit, class:'btn btn-outline-info font-s'%>
    <% end %>
    <br>

    <% if @review.errors.any? %>
        <% @review.errors.full_messages.each do |msg| %>
            <div class="alert alert-warning font-s" role="alert">    
                <%= msg%>
            </div>
        <% end%>
    <% end%>
    
    <% @reviews.each do |review| %>
        <div class= "example font text-dark">
        <%= review.body%>
        </div>

        <p class="font-s text-secondary">
        Posted <%= time_ago_in_words(review.created_at) %> ago
        |
        Created by: <%= review.user.full_name %>
        |
        <% if can?(:crud, review)%>
            <%= link_to "Delete", idea_review_path(@idea.id, review.id), class: 'badge badge-info font-xs ', method: :delete, data:{confirm: "Are you sure?"}  %>
        <% end %>

        
        </p>

    <% end %>
    <hr>
</div>

ideas/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ideas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>

  <nav class="navbar navbar-light bg-light justify-content-between">
    <ul class="nav">
      <a href="/" class="nav-link ml heading text-info">Idea Factory</a>
    </ul>
    <ul class="nav">
    <li><a href="/ideas/new" class="nav-link mr font text-info">Create new Idea</a></li>
    
  <% if user_signed_in? %>
      <li class= "nav-link text-dark font">
        Hello! <%= current_user.full_name%>
      </li>
        <li><%= link_to "Logout", session_path, class: 'nav-link mr font text-info', method: :delete, data: {confirm: "Are you sure you want to logout?"} %></li>
        <% else %>
        <li><%=  link_to  'Log in', new_session_path, class: 'nav-link mr font text-info'  %></li>
        <li><%=  link_to  'Sign Up', new_user_path, class: 'nav-link mr font text-info' %></li>
      <% end %>
    </ul>
</nav>

  <% if flash[:notice].present?%>
    <div class="alert alert-success alert-dismissible fade show font-s" role="alert">
      <%= flash[:notice]%>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">
            &times;
          </span>
          </button>
        </div>
        
    <% elsif flash[:alert].present?%>
      <div class="alert alert-danger alert-dismissible fade show font-s" role="alert">
          <%= flash[:alert]%>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">
            &times;
          </span>
          </button>
      </div>

    <% end %>

    <%= yield %>
  </body>
</html>

ideas/app/views/users/new.html.erb
<div class="container-fluid">
    <h3 class = "heading bold">Sign Up</h3>

    <%= form_with model: @user do |form| %>
        <% if @user.errors.any?%>
            <div class="alert alert-warning font-s" role="alert"> 
                <p><%= @user.errors.full_messages.join(', ')%></p>
            </div>
        <% end%>
        <div>
            <%= form.label :first_name, class:"font-s"%>
            <%= form.text_field :first_name, class:"form-control font-s"%>
        </div>
        <div>
            <%= form.label :last_name, class:"font-s"%>
            <%= form.text_field :last_name, class:"form-control font-s"%>
        </div>
        <div>
            <%= form.label :email, class:"font-s"%>
            <%= form.text_field :email, class:"form-control font-s"%>
        </div>
        <div>
            <%= form.label :password, class:"font-s"%>
            <%= form.text_field :password, class:"form-control font-s" , type:"password"%>
        </div>
        <div>
            <%= form.label :password_confirmation, class:"font-s"%>
            <%= form.text_field :password_confirmation, class:"form-control font-s", type:"password"%>
        </div>
        <br>
        <%= form.submit "Sign Up", class: 'btn btn-outline-info font-s'%>
    <% end %>